games/trenchbroom: try to unreak the port's build on recent -CURRENT
  common/src/BBox.h:174:33: error: no member named 'insersectWith'
  in 'BBox<T, S>'; did you mean 'intersectWith'?
  174 |		return BBox<T,S>(*this).insersectWith(right);

Interestingly, this small typo in the member name did not cause build
failure before.

Reported by:	pkg-fallout