www/mod_perl2: fix build with clang 19 on i386
Clang 19 has become more strict about incompatible function pointer
types, which results in an error building mod_perl2 on i386:

  modperl_common_util.c:57:53: error: incompatible function pointer types initializing 'int (*)(PerlInterpreter *, SV *, MAGIC *, SV *, const char *, I32)' (aka 'int (*)(struct interpreter *, struct sv *, struct magic *, struct sv *, const char *, long)') with an expression of type 'int (PerlInterpreter *, SV *, MAGIC *, SV *, const char *, int)' (aka 'int (struct interpreter *, struct sv *, struct magic *, struct sv *, const char *, int)') [-Wincompatible-function-pointer-types]
     57 |                                                     modperl_table_magic_copy};
        |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~

Perl uses the type `I32` for the last parameter, which is apparently
`long` on i386. So use that instead.

PR:		281594
MFH:		2024Q3