www/py-django-graphiql-debug-toolbar: Fix runtime after f8392fba5cb4
* Add a workaround for py-django-debug-toolbar 4.4.6 or newer to prevent
  following error [1]:

  [...]
    File "/usr/local/lib/python3.11/site-packages/graphiql_debug_toolbar/middleware.py", line 7, in <module>
        from debug_toolbar.middleware import _HTML_TYPES
    ImportError: cannot import name '_HTML_TYPES' from 'debug_toolbar.middleware' (/usr/local/lib/python3.11/site-packages/debug_toolbar/middleware.py)
  [...]

* Switch to the PEP517 build framework while I'm here.

* Bump PORTREVISION due package change.

PR:		280254 [1]
Reported by:	Fredrik Eriksson [1]