sysutils/superiotool: fix build after pci after libpci 3.14.0 update
The libpci update introduced a C++ style comment ('//') into a header file.
superiotool uses very strict compilation flags (including -ansi), so its
build started to fail with:
  /usr/local/include/pci/header.h:1691:45: error: // comments are not
  allowed in this language [-Werror,-Wcomment]
Fix the problem by adding -Wno-comment exemption.