devel/libgit2: Ensure LOCALBASE/include is in the include path
Add USES=localbase.

[  1% 9/188] cc  -isystem /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/include -isystem /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/src/util -isystem /wrkdirs/usr/ports/devel/libgit2/work/.build/src/util -D_GNU_SOURCE -O2 -pipe  -fno-strict-aliasing -Wall -Wextra -fvisibility=hidden -fPIC -Wdocumentation -Wno-documentation-deprecated-sync -Wno-missing-field-initializers -Wmissing-declarations -Wstrict-aliasing -Wstrict-prototypes -Wdeclaration-after-statement -Wshift-count-overflow -Wunused-const-variable -Wunused-function -Wint-conversion -Wc11-extensions -Wformat -Wformat-security -O2 -pipe  -fno-strict-aliasing  -DNDEBUG -Wno-sign-compare -MD -MT deps/xdiff/CMakeFiles/xdiff.dir/xpatience.c.o -MF deps/xdiff/CMakeFiles/xdiff.dir/xpatience.c.o.d -o deps/xdiff/CMakeFiles/xdiff.dir/xpatience.c.o -c /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/deps/xdiff/xpatience.c
FAILED: deps/xdiff/CMakeFiles/xdiff.dir/xpatience.c.o
cc  -isystem /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/include -isystem /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/src/util -isystem /wrkdirs/usr/ports/devel/libgit2/work/.build/src/util -D_GNU_SOURCE -O2 -pipe  -fno-strict-aliasing -Wall -Wextra -fvisibility=hidden -fPIC -Wdocumentation -Wno-documentation-deprecated-sync -Wno-missing-field-initializers -Wmissing-declarations -Wstrict-aliasing -Wstrict-prototypes -Wdeclaration-after-statement -Wshift-count-overflow -Wunused-const-variable -Wunused-function -Wint-conversion -Wc11-extensions -Wformat -Wformat-security -O2 -pipe  -fno-strict-aliasing  -DNDEBUG -Wno-sign-compare -MD -MT deps/xdiff/CMakeFiles/xdiff.dir/xpatience.c.o -MF deps/xdiff/CMakeFiles/xdiff.dir/xpatience.c.o.d -o deps/xdiff/CMakeFiles/xdiff.dir/xpatience.c.o -c /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/deps/xdiff/ xpatience.c
In file included from /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/deps/xdiff/xpatience.c:22:
In file included from /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/deps/xdiff/xinclude.h:26:
In file included from /wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/deps/xdiff/git-xdiff.h:17:
/wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.7.2/src/util/regexp.h:19:11: fatal error: 'pcre2.h' file not found
 # include <pcre2.h>
           ^~~~~~~~~
1 error generated.