devel/py-pynest2d: broken on ARM due to boost error
Mark as broken from a boost error.

/usr/local/include/boost/qvm/quat_traits.hpp:92:30: error: a template argument l
ist is expected after a name prefixed by the template keyword [-Wmissing-templat
e-arg-list-after-template-kw]
   92 |     quat_traits<Q>::template write_element_idx(i, q, s);
      |                              ^