benchmarks/rubygem-derailed_benchmarks: Change RUN_DEPENDS from rubygem-get_process_mem to rubygem-get_process_mem0
- Fix version requirement of RUN_DEPENDS
- Bump PORTREVISION for dependency change

from derailed_benchmarks.gemspec [1]:
  gem.add_dependency "get_process_mem", "~> 0"

Note that this port still does not pass stage-qa.
====> Running Q/A tests (stage-qa)
Error: RubyGem dependency memory_profiler ~> 0 is not satisfied.
*** Error code 1

This port can be removed since it is not used by any port.

Reference:	https://github.com/zombocom/derailed_benchmarks/blob/v1.7.0/derailed_benchmarks.gemspec#L27 [1]