www/tor-browser: fix build: "pub _base: root::std::__1::_And<_Pred>, not found in this scope"
error[E0412]: cannot find type `_Pred` in this scope
     --> /tmp/work/usr/ports/www/tor-browser/work/.build/x86_64-unknown-freebsd/release/build/style-ea1857e57f097f7a/out/gecko/structs.rs:34456:49
      |
34456 |                 pub _base: root::std::__1::_And<_Pred>,
      |                                                 ^^^^^ not found in this scope
      |
help: you might be missing a type parameter
      |
34455 |             pub struct tuple__EnableUTypesCtor<_Pred> {
      |                                               +++++++

Add patches from www/firefox-esr to fix this error and other.

PR:		279693
Approved by:	Martin Filla <freebsd@sysctl.cz> (maintainer)