databases/sfcgal: fix build with clang 19
Clang 19 now diagnoses incorrect member accesses, which causes
databases/sfcgal to fail with errors similar to:

    /wrkdirs/usr/ports/databases/sfcgal/work/CGAL-5.6.1/include/CGAL/boost/graph/iterator.h:219:22: error: no member named 'base' in 'Halfedge_around_source_iterator<Graph>'
      219 |     return (! (this->base() == nullptr));
          |                ~~~~  ^
    /wrkdirs/usr/ports/databases/sfcgal/work/CGAL-5.6.1/include/CGAL/boost/graph/iterator.h:313:22: error: no member named 'base' in 'Halfedge_around_target_iterator<Graph>'
      313 |     return (! (this->base() == nullptr));
          |                ~~~~  ^
    /wrkdirs/usr/ports/databases/sfcgal/work/CGAL-5.6.1/include/CGAL/boost/graph/iterator.h:405:22: error: no member named 'base' in 'Halfedge_around_face_iterator<Graph>'
      405 |     return (! (this->base() == nullptr));
          |                ~~~~  ^

Upstream fixed this in https://github.com/CGAL/cgal/commit/0de060acd68
but it does not apply easily due to some changed context. Add a
backported patch instead.

PR:		280737
Approved by:	maintainer timeout (2 weeks)
MFH:		2024Q3