net/samba419: Require the right version of unbundled tdb
When building with SAMBA4_BUNDLED_TDB=no, the configure target errors out with
the following message:

> Checking for system tdb (>=1.4.9) : not found
> ERROR: System library tdb of version 1.4.9 not found, and bundling disabled
> ===>  Script "configure" failed unexpectedly.

Update the version requirements in the makefile accordingly.

To address this properly, we need to bring databases/tdb 1.4.9 to the ports
tree.

Approved by:	portmgr blanket
Fixes:		b0a4fa4a12b0 net/samba419: Add new port
Sponsored by:	Klara, Inc.