net-p2p/transmission-components: Fix build with miniupnpc-2.2.8
/usr/ports/net-p2p/transmission-components/work-cli/transmission-4.0.6/libtransmission/port-forwarding-upnp.cc:278:13:
error: no matching function for call to 'UPNP_GetValidIGD'
  278 |         if (UPNP_GetValidIGD(devlist, &handle->urls,
&handle->data, std::data(lanaddr), std::size(lanaddr) - 1) ==
      |             ^~~~~~~~~~~~~~~~
/usr/local/include/miniupnpc/miniupnpc.h:122:1: note: candidate function
not viable: requires 7 arguments, but 5 were provided
  122 | UPNP_GetValidIGD(struct UPNPDev * devlist,
      | ^                ~~~~~~~~~~~~~~~~~~~~~~~~~
  123 |                  struct UPNPUrls * urls,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~
  124 |                  struct IGDdatas * data,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~
  125 |                  char * lanaddr, int lanaddrlen,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  126 |                  char * wanaddr, int wanaddrlen);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
*** Error code 1

PR:		280298
Approved by:	Rafe <mondo.debater_0q@icloud.com> (maintainer)
Obtained from:	https://github.com/transmission/transmission/commit/febfe49ca3ecab1a7142ecb34012c1f0b2bcdee8