x11-wm/labwc: install new translations after 84fca1b3c86b
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/locale/da/LC_MESSAGES/labwc.mo
Error: Orphaned: share/locale/pt_BR/LC_MESSAGES/labwc.mo
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Reported by:	QAT