x11/waylock: update to 1.2.1 after b2b3906286ed
waylock-1.1.0/build.zig:39:30: error: no field named 'path' in union 'Build.LazyPath'
/usr/local/lib/zig/std/Build.zig:2171:22: note: union declared here

PR:		279604
Changes:	https://codeberg.org/ifreund/waylock/releases/tag/v1.2.0
Changes:	https://codeberg.org/ifreund/waylock/releases/tag/v1.2.1
Reported by:	Repology