www/shiori: Update to 1.7.0
- Increment the go version required by the port to build
- Add a patch to fix the following error during the build target:

internal/database/database.go:59:10: undefined: OpenSQLiteDatabase

See also: https://github.com/go-shiori/shiori/issues/947

Release changes:	https://github.com/go-shiori/shiori/releases/tag/v1.7.0
Reported by:	github-actions[bot] <notifications@github.com>