devel/llvm13: fix build with clang 19
Clang 19 now implements CWG 96 [1], which requires a template argument
list after a 'template' keyword, resulting in errors similar to:

  /wrkdirs/usr/ports/devel/llvm13/work/llvm-project-13.0.1.src/flang/include/flang/Evaluate/integer.h:310:32: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
    310 |       auto back{FROM::template ConvertSigned(result.value)};
        |                                ^

Upstream has committed a fix to their main branch [2], but it does not
apply cleanly to 13.0.1, so add a backported patch.

[1] https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#96
[2] https://github.com/llvm/llvm-project/commit/7bc7672925f8154be3b8220365d3f269ac43621c

PR:		281486
Approved by:	brooks (maintainer)
MFH:		2024Q3