math/maxima: build fix (mandir, makeinfo)
Remove create unneeded and unsupported PREFIX/man/man1 directory (causes
Error: Orphaned: @dir man/man1).

Fix makeinfo version checking error in configure:
- replace backtick to brackets and dollar sign
- use gexpr instead of builtin expr (add sysutils/coreutils to
  BULD_DEPENDS and use BINARY_ALIAS)
The makeinfo_version_string variable is empty because the backslashes
remain before backticks, do not appear. And the regexp is not compatible
with shipped expr so shoud use GNU expr.