lang/zig: pacify check-plist after 8c1e3e605452
4b6d52cef587 claimed to fix but didn't:

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: /wrkdirs/usr/ports/lang/zig/work/.build/stage3/bin/zig
Error: Orphaned: /wrkdirs/usr/ports/lang/zig/work/.build/stage3/lib/zig/build_runner.zig
Error: Orphaned: /wrkdirs/usr/ports/lang/zig/work/.build/stage3/lib/zig/c.zig
Error: Orphaned: /wrkdirs/usr/ports/lang/zig/work/.build/stage3/lib/zig/compiler_rt.zig
Error: Orphaned: /wrkdirs/usr/ports/lang/zig/work/.build/stage3/lib/zig/compiler_rt/aarch64_outline_atomics.zig
Error: Orphaned: /wrkdirs/usr/ports/lang/zig/work/.build/stage3/lib/zig/compiler_rt/absv.zig
Error: Orphaned: /wrkdirs/usr/ports/lang/zig/work/.build/stage3/lib/zig/compiler_rt/absvdi2.zig
[...]
Error: Orphaned: @dir lib/zig/std/compress/lzma/testdata
Error: Orphaned: @dir lib/zig/std/compress/xz/testdata
[...]

PR:		278570
Differential Revision:	https://reviews.freebsd.org/D45024