x11-wm/wayfire: add missing dependency after e2adbb0f90a6
Found via wayfire-plugins-extra 0.9.0.

In file included from ../src/view-shot.cpp:27:
/usr/local/include/wayfire/plugins/ipc/ipc-helpers.hpp:10:10: fatal error: 'nlohmann/json.hpp' file not found
   10 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~