mail/dspam: fix configure with modern MariaDB
1) Configure fails with error message:
checking for MySQL client version >= 5.0.0... no
configure: error: Required version of libmysqlclient not found

It check "mysql_get_client_info() > 5", but modern MariaDB return
Connector/C's version 3.x instead of MariaDB version.
How to get the correct version found here:
https://github.com/pali/DBD-MariaDB/commit/9743bec52db5e8f1beb2b31e4a55d6ea1a4edcdd

While here:
2) remove GNU_CONFIGURE_MANPREFIX
3) fix make check-plist if build with MYSQL option ON only:
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir lib/%%DSPAM_OWNER%%

PR:		279253
Approved by:	danny@dannywarren.com (maintainer, timeout 17 days)