sysutils/isomaster: fix build
./settings.h:10:10: fatal error: 'iniparser.h' file not found
   10 | #include <iniparser.h>

While here, also update to 1.3.17.