print/py-uharfbuzz: update to 0.45.0 after 2f2cc06bb921
src/uharfbuzz/_harfbuzz.cpp:1288:10: fatal error: 'hb-subset-repacker.h' file not found
 1288 | #include "hb-subset-repacker.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~

Changes:	https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.45.0
Reported by:	GitHub (watch releases)
PR:		284008