benchmarks/rubygem-gitlab-derailed_benchmarks: Change RUN_DEPENDS from rubygem-get_process_mem to rubygem-get_process_mem0
- Fix version requirement of RUN_DEPENDS
- Bump PORTREVISION for dependency change

from gitlab-derailed_benchmarks.gemspec:
  s.add_runtime_dependency(%q<get_process_mem>.freeze, ["~> 0".freeze])

Note that this port still does not pass stage-qa.
====> Running Q/A tests (stage-qa)
Error: RubyGem dependency memory_profiler ~> 0 is not satisfied.
*** Error code 1

This port can be removed since it is not used by any port.