devel/electron*: Fix build on main
After src snapshot 0c47b9c211, the build began failing with:

../../third_party/nasm/include/compiler.h:249:21: error: static
 declaration of 'mempcpy' follows non-static declaration
  249 | static inline void *mempcpy(void *dst, const void *src, size_t n)
      |                     ^
/usr/include/string.h:71:8: note: previous declaration is here
   71 | void    *(mempcpy)(void * __restrict, const void * __restrict, size_t);
      |           ^

- Restore a default definition of HAVE_MEMPCPY to indicate that
  mempcpy(3) is available.  It has been part of FreeBSD since 13.1.

- Remove a patch used to detect mempcpy(3) in /usr/include/string.h.  It
  is no longer necessary and does not detect the function after src
  snapshot 0c47b9c211.

Approved by:	tagattie (maintainer)
Sponsored by:	The FreeBSD Foundation
Differential Revision:	https://reviews.freebsd.org/D46054