graphics/mesa-dri: Fix 15-CURRENT 108de784513d build
108de784513d on main in src redefined CLOCK_BOOTTIME to alias
CLOCK_MONOTONIC, instead of CLOCK_UPTIME. This results in the following
errors when building this port under 15-CURRENT:

../src/intel/common/xe/intel_gem.c:72:9: error: duplicate case value '4'
   72 |    case CLOCK_BOOTTIME:
      |         ^
/usr/include/sys/_clock_id.h:81:25: note: expanded from macro
'CLOCK_BOOTTIME'
   81 | #define CLOCK_BOOTTIME          CLOCK_MONOTONIC
      |                                 ^
/usr/include/sys/_clock_id.h:56:26: note: expanded from macro
'CLOCK_MONOTONIC'
   56 | #define CLOCK_MONOTONIC         4
      |                                 ^
../src/intel/common/xe/intel_gem.c:66:9: note: previous case defined here
   66 |    case CLOCK_MONOTONIC:
      |         ^
/usr/include/sys/_clock_id.h:56:26: note: expanded from macro
'CLOCK_MONOTONIC'
   56 | #define CLOCK_MONOTONIC         4
      |                                 ^
1 error generated.

On FreeBSD systems without 108de784513d the old definition will be used
while on 108de784513d and newer the duplicate case will be removed.

Repored by:	eduardo
Obtained from:	src 676041c41ba5
Discussed with: imp