ftp/R-cran-curl: Update to 0.6.1
Remove R-cran-magrittr from TEST_DEPENDS.
Add TESTING_UNSAFE=yes:
* checking running R code from vignettes ...
  'intro.Rmd' using 'UTF-8'... failed
  'windows.Rmd' using 'UTF-8'... OK
 ERROR
Errors in running code in vignettes:
when running code in 'intro.Rmd'
  ...

> mirros <- read.csv("mirrors.csv")

> unlink("mirrors.csv")

> close(con)

  When sourcing 'intro.R':
Error: invalid connection
Execution halted

PR:		282908